#!/usr/bin/env bash
# DEBSWAY_DESC: Firefox ESR + Betterfox hardening
# DEBSWAY_DEFAULT: Y
#  16-firefox.sh — install & harden Firefox ESR
#  System-wide defaults architecture (inspired by your own
#  Butterbian-XFCE /etc/firefox-esr/butterbian.js approach)
#  instead of a per-profile user.js + wrapper script:
#
#    Debian's firefox-esr reads every *.js file in
#    /etc/firefox-esr/ at startup and applies them as DEFAULT
#    prefs for every profile, for every user on the system.
#    This is more robust than a per-profile user.js: it covers
#    new profiles automatically, survives Firefox updates
#    cleanly, and doesn't need a launcher-wrapper trick to stay
#    fresh. It sits alongside the package's own
#    /etc/firefox-esr/firefox-esr.js untouched, and alongside
#    /usr/lib/firefox-esr/distribution/policies.json.
#
#  Betterfox is still fetched LIVE from upstream at install
#  time (never bundled/hardcoded here), then converted from
#  user_pref() to pref() syntax — system-default files use
#  pref(), not user_pref().
#
#  Note for future maintenance: Firefox applies "first pref()
#  wins" semantics across all files in /etc/firefox-esr/, so if
#  a specific Betterfox value ever needs overriding, it has to
#  be sed-patched in place in the fetched content rather than
#  appended afterward — an append can't win over an earlier
#  declaration of the same pref.
#  Privilege: priv() (doas-first, sudo fallback)
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

require_not_root
# NOTE: deliberately not using -e — several independent stages here,
# one failing shouldn't necessarily abort the rest.



BETTERFOX_TAG=150.0
BETTERFOX_URL="https://raw.githubusercontent.com/yokoffing/Betterfox/${BETTERFOX_TAG}/user.js"
DEFAULTS_FILE="/etc/firefox-esr/devuan-xfce-setup.js"



if [[ ! -f "$SCRIPT_DIR/policies.json" ]]; then
    log_err "policies.json not found in $SCRIPT_DIR"; exit 1
fi

log_head "1/3  Install firefox-esr"
if is_installed firefox-esr; then
    log_ok "firefox-esr already installed."
else
    log_info "Installing firefox-esr..."
    apt_update || log_warn "apt-get update failed (continuing with cached lists)."
    if priv apt-get install -y firefox-esr; then
        log_ok "firefox-esr installed."
    else
        log_err "Failed to install firefox-esr."; exit 1
    fi
fi

log_head "2/3  System-wide default prefs (/etc/firefox-esr/)"
# The fetch below needs curl (absent on minimal netinsts — 33 installs it
# much later, so ensure it here instead of dying with exit 1).
install_pkgs "Downloader" curl || { log_err "curl missing, can't fetch Betterfox."; exit 1; }
log_info "Fetching Betterfox ${BETTERFOX_TAG}..."
TMP_JS="$(mktemp)"
trap 'rm -f "$TMP_JS"' EXIT

if curl -fL "$BETTERFOX_URL" -o "$TMP_JS"; then
    {
        cat <<HEADER
// Firefox ESR system-wide defaults — Betterfox ${BETTERFOX_TAG} + additions.
// Generated by scripts/16-firefox.sh — re-run to refresh from upstream.
// Applies to every profile on this system. Sits alongside (and doesn't
// touch) the package-shipped /etc/firefox-esr/firefox-esr.js.
//
// To bump Betterfox: set BETTERFOX_TAG below to the new release, re-run,
// then diff the fetched user.js between the BEGIN/END markers and re-apply
// any "DIVERGENCE" edits in place ("first pref() wins" — they cannot live
// in ADDITIONS).
//
// ============================================================================
// BEGIN BETTERFOX ${BETTERFOX_TAG} — adapted from https://github.com/yokoffing/Betterfox
// (user_pref → pref conversion for system-defaults delivery)
// ============================================================================

HEADER
        # System-default files use pref(), not user_pref().
        sed 's/^user_pref(/pref(/' "$TMP_JS"
        cat <<'ADDITIONS'
// ============================================================================
// END BETTERFOX — everything below is ours
// ============================================================================

// ============================================================================
// ADDITIONS — Linux-targeted, intentional, minimal
// ============================================================================
pref("signon.autofillForms", false);
pref("geo.provider.use_geoclue", false);
pref("pdfjs.defaultZoomValue", "page-width");
pref("browser.firefox-view.feature-tour", "{\"screen\":\"\",\"complete\":true}");
// Follow the Darkmatter dark desktop — no white-flash on new profiles.
pref("ui.systemUsesDarkTheme", 1);
pref("browser.theme.content-theme", 0);
pref("browser.theme.toolbar-theme", 0);
ADDITIONS
    } | priv tee "$DEFAULTS_FILE" > /dev/null
    priv chmod 0644 "$DEFAULTS_FILE"
    log_ok "Defaults written to $DEFAULTS_FILE"
else
    log_err "Failed to fetch Betterfox from $BETTERFOX_URL"; exit 1
fi

log_head "3/3  Enterprise policies (uBlock Origin, search engines, telemetry)"
DISTRIBUTION_DIR="/usr/lib/firefox-esr/distribution"
[[ ! -d "$DISTRIBUTION_DIR" ]] && priv mkdir -p "$DISTRIBUTION_DIR"
if priv cp "$SCRIPT_DIR/policies.json" "$DISTRIBUTION_DIR/policies.json"; then
    log_ok "Policies installed to $DISTRIBUTION_DIR"
else
    log_warn "Failed to install policies.json"
fi

log_ok "Firefox ESR hardening complete."
log_warn "Restart Firefox (or start it fresh) for the new defaults to take effect."
