#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════
#  firefoxHarden.sh — install & harden Firefox ESR
#  System-wide defaults architecture (inspired by your own
#  Butterbian-XFCE /etc/firefox-esr/butterbian.js approach)
#  instead of a per-profile user.js + wrapper script:
#
#    Debian's firefox-esr reads every *.js file in
#    /etc/firefox-esr/ at startup and applies them as DEFAULT
#    prefs for every profile, for every user on the system.
#    This is more robust than a per-profile user.js: it covers
#    new profiles automatically, survives Firefox updates
#    cleanly, and doesn't need a launcher-wrapper trick to stay
#    fresh. It sits alongside the package's own
#    /etc/firefox-esr/firefox-esr.js untouched, and alongside
#    /usr/lib/firefox-esr/distribution/policies.json.
#
#  Betterfox is still fetched LIVE from upstream at install
#  time (never bundled/hardcoded here), then converted from
#  user_pref() to pref() syntax — system-default files use
#  pref(), not user_pref().
#
#  Note for future maintenance: Firefox applies "first pref()
#  wins" semantics across all files in /etc/firefox-esr/, so if
#  a specific Betterfox value ever needs overriding, it has to
#  be sed-patched in place in the fetched content rather than
#  appended afterward — an append can't win over an earlier
#  declaration of the same pref.
#  Privilege: sudo
# ══════════════════════════════════════════════════════════════
set -uo pipefail
# NOTE: deliberately not using -e — several independent stages here,
# one failing shouldn't necessarily abort the rest.

R="\e[31m" G="\e[32m" Y="\e[33m" B="\e[34m" C="\e[36m" W="\e[1m" Z="\e[0m"
info()  { echo -e "${B}${W}[INFO]${Z} $*"; }
ok()    { echo -e "${G}${W}[ ✔ ]${Z} $*"; }
warn()  { echo -e "${Y}${W}[ ! ]${Z} $*"; }
err()   { echo -e "${R}${W}[ ✖ ]${Z} $*"; }
step()  { echo -e "\n${C}${W}══ $* ══${Z}"; }

[[ $EUID -eq 0 ]] && { err "Run this script as your normal user, not root."; exit 1; }
command -v sudo &>/dev/null || { err "sudo not found."; exit 1; }

BETTERFOX_TAG=150.0
BETTERFOX_URL="https://raw.githubusercontent.com/yokoffing/Betterfox/${BETTERFOX_TAG}/user.js"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULTS_FILE="/etc/firefox-esr/devuan-xfce-setup.js"

is_installed() { dpkg-query -W -f='${Status}' "$1" 2>/dev/null | grep -q "install ok installed"; }

echo -e "\n${B}${W}══════ Firefox ESR Hardening ══════${Z}"

if [[ ! -f "$SCRIPT_DIR/policies.json" ]]; then
    err "policies.json not found in $SCRIPT_DIR"; exit 1
fi

step "1/3  Install firefox-esr"
if is_installed firefox-esr; then
    ok "firefox-esr already installed."
else
    info "Installing firefox-esr..."
    sudo apt-get update -qq
    if sudo apt-get install -y firefox-esr; then
        ok "firefox-esr installed."
    else
        err "Failed to install firefox-esr."; exit 1
    fi
fi

step "2/3  System-wide default prefs (/etc/firefox-esr/)"
info "Fetching Betterfox ${BETTERFOX_TAG}..."
TMP_JS="$(mktemp)"
trap 'rm -f "$TMP_JS"' EXIT

if curl -fL "$BETTERFOX_URL" -o "$TMP_JS"; then
    {
        cat <<HEADER
// Firefox ESR system-wide defaults — Betterfox ${BETTERFOX_TAG} + additions.
// Generated by scripts/firefoxHarden.sh — re-run to refresh from upstream.
// Applies to every profile on this system. Sits alongside (and doesn't
// touch) the package-shipped /etc/firefox-esr/firefox-esr.js.

HEADER
        # System-default files use pref(), not user_pref().
        sed 's/^user_pref(/pref(/' "$TMP_JS"
        cat <<'ADDITIONS'

// ============================================================================
// ADDITIONS — Linux-targeted, intentional, minimal
// ============================================================================
pref("signon.autofillForms", false);
pref("geo.provider.use_geoclue", false);
pref("pdfjs.defaultZoomValue", "page-width");
pref("browser.firefox-view.feature-tour", "{\"screen\":\"\",\"complete\":true}");
ADDITIONS
    } | sudo tee "$DEFAULTS_FILE" > /dev/null
    sudo chmod 0644 "$DEFAULTS_FILE"
    ok "Defaults written to $DEFAULTS_FILE"
else
    err "Failed to fetch Betterfox from $BETTERFOX_URL"; exit 1
fi

step "3/3  Enterprise policies (uBlock Origin, search engines, telemetry)"
DISTRIBUTION_DIR="/usr/lib/firefox-esr/distribution"
[[ ! -d "$DISTRIBUTION_DIR" ]] && sudo mkdir -p "$DISTRIBUTION_DIR"
if sudo cp "$SCRIPT_DIR/policies.json" "$DISTRIBUTION_DIR/policies.json"; then
    ok "Policies installed to $DISTRIBUTION_DIR"
else
    warn "Failed to install policies.json"
fi

ok "Firefox ESR hardening complete."
warn "Restart Firefox (or start it fresh) for the new defaults to take effect."
